import Head from "next/head";
import { useRouter } from "next/router";
import type { NextPage } from "next/types";

const About: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>RateMyHousing - {id}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full gap-4 py-4 px-6 lg:px-36"></div>
    </>
  );
};

export default About;
